package arsw.laberinto;

import javax.swing.*;

/**
 *
 * @author pegasusmax
 */
public class ServerFrame extends JFrame {

    public ServerFrame(String name, String ip) {
        super(name);
        initComponents();
        setIP(ip);
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    private void setIP(String ip) {
        ipValue.setText(ip);
    }

    private void exit() {
        dispose();
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        turnOff = new javax.swing.JButton();
        serverReady = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        ipAddr = new javax.swing.JLabel();
        ipValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        turnOff.setText("Turn off");
        turnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnOffActionPerformed(evt);
            }
        });

        serverReady.setText("Server ready.");

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel.setToolTipText("");

        ipAddr.setText("IP Address:");

        ipValue.setEditable(false);
        ipValue.setText("255.255.255.255");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ipValue, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ipAddr)
                .addGap(24, 24, 24))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(ipAddr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(serverReady))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(turnOff))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(serverReady)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(turnOff))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void turnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnOffActionPerformed
        exit();
    }//GEN-LAST:event_turnOffActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ipAddr;
    private javax.swing.JTextField ipValue;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel serverReady;
    private javax.swing.JButton turnOff;
    // End of variables declaration//GEN-END:variables
}
